---
- name: Troublesome Playbook
  hosts: all
  become: yes
  vars:
    install_package: "vsftpd"
    service_name: "vfstpd"

  tasks:
  - name: Install a package
    yum
      name: "{{ install_packge }}"
      state: "installed

  - name: Start and enable a service
    services:
    name: "{{ service-name }}"
    enabled: yes
    state started
